name: PHPstan and PHPunit CI
run-name: ${{ github.actor}} runs PHPstan and PHPunit CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - development
  pull_request:
    branches:
      - main
      - master
      - development

jobs:
  ci-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: php-actions/composer@v6
        with:
          php_version: 8.5
        env:
          COMPOSER_ROOT_VERSION: dev-master
      - name: "Restore result cache"
        uses: actions/cache/restore@v5
        with:
          path: ./tmp
          key: "result-cache-v1-${{ matrix.php-version }}-${{ github.run_id }}"
          restore-keys: |
            result-cache-v1-${{ matrix.php-version }}-
      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: src/
          configuration: phpstan.neon
      - name: "Save result cache"
        uses: actions/cache/save@v5
        if: always()
        with:
          path: ./tmp
          key: "result-cache-v1-${{ matrix.php-version }}-${{ github.run_id }}"
          # We need to use phpunit from the self install to get the class paths
      - name: PHPunit Tests
        run: |
          vendor/bin/phpunit
